server:
  port: 8071
spring:
  application:
    name: cars-list
  datasource:
    url: jdbc:postgresql://localhost:5432/cars_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

aws:
  s3:
    photos-folder: ${AWS_FOLDER}
    region: ${AWS_REGION:eu-central-1}
    bucket: ${AWS_BUCKET}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key:
    ${JWT_SECRET_KEY:1F2D3G4H5J6K7L8M9N0PQ1RST2UV3WX4YZ5A6BC7DE8FG9HI0JK1LM2NO3PQ4RS}
  expiration:
    3600000

scheduler:
  cache:
    period: '0 0 * * * *'